#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MOE_DDatabase")]
public partial class MOE_DataClassModelDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertacademicYear(academicYear instance);
  partial void UpdateacademicYear(academicYear instance);
  partial void DeleteacademicYear(academicYear instance);
  partial void Insertassessment(assessment instance);
  partial void Updateassessment(assessment instance);
  partial void Deleteassessment(assessment instance);
  partial void Insertedu_officerComment(edu_officerComment instance);
  partial void Updateedu_officerComment(edu_officerComment instance);
  partial void Deleteedu_officerComment(edu_officerComment instance);
  partial void Insertedu_officer(edu_officer instance);
  partial void Updateedu_officer(edu_officer instance);
  partial void Deleteedu_officer(edu_officer instance);
  partial void Insertedu_officerSubject(edu_officerSubject instance);
  partial void Updateedu_officerSubject(edu_officerSubject instance);
  partial void Deleteedu_officerSubject(edu_officerSubject instance);
  partial void Insertformclass(formclass instance);
  partial void Updateformclass(formclass instance);
  partial void Deleteformclass(formclass instance);
  partial void InsertgeneralObjective(generalObjective instance);
  partial void UpdategeneralObjective(generalObjective instance);
  partial void DeletegeneralObjective(generalObjective instance);
  partial void InsertgradeBook(gradeBook instance);
  partial void UpdategradeBook(gradeBook instance);
  partial void DeletegradeBook(gradeBook instance);
  partial void InsertinstructionalMaterial(instructionalMaterial instance);
  partial void UpdateinstructionalMaterial(instructionalMaterial instance);
  partial void DeleteinstructionalMaterial(instructionalMaterial instance);
  partial void InsertlessonPlanMethod(lessonPlanMethod instance);
  partial void UpdatelessonPlanMethod(lessonPlanMethod instance);
  partial void DeletelessonPlanMethod(lessonPlanMethod instance);
  partial void InsertlessonplanPlanactivite(lessonplanPlanactivite instance);
  partial void UpdatelessonplanPlanactivite(lessonplanPlanactivite instance);
  partial void DeletelessonplanPlanactivite(lessonplanPlanactivite instance);
  partial void InsertlessonplanPlancomment(lessonplanPlancomment instance);
  partial void UpdatelessonplanPlancomment(lessonplanPlancomment instance);
  partial void DeletelessonplanPlancomment(lessonplanPlancomment instance);
  partial void InsertlessonPlan(lessonPlan instance);
  partial void UpdatelessonPlan(lessonPlan instance);
  partial void DeletelessonPlan(lessonPlan instance);
  partial void InsertlessonplanSpecificobjective(lessonplanSpecificobjective instance);
  partial void UpdatelessonplanSpecificobjective(lessonplanSpecificobjective instance);
  partial void DeletelessonplanSpecificobjective(lessonplanSpecificobjective instance);
  partial void InsertlesssonPlanStep(lesssonPlanStep instance);
  partial void UpdatelesssonPlanStep(lesssonPlanStep instance);
  partial void DeletelesssonPlanStep(lesssonPlanStep instance);
  partial void Insertmethod(method instance);
  partial void Updatemethod(method instance);
  partial void Deletemethod(method instance);
  partial void Insertplanactivity(planactivity instance);
  partial void Updateplanactivity(planactivity instance);
  partial void Deleteplanactivity(planactivity instance);
  partial void Insertplancomment(plancomment instance);
  partial void Updateplancomment(plancomment instance);
  partial void Deleteplancomment(plancomment instance);
  partial void InsertspecificObjective(specificObjective instance);
  partial void UpdatespecificObjective(specificObjective instance);
  partial void DeletespecificObjective(specificObjective instance);
  partial void Insertstep(step instance);
  partial void Updatestep(step instance);
  partial void Deletestep(step instance);
  partial void Insertstudent(student instance);
  partial void Updatestudent(student instance);
  partial void Deletestudent(student instance);
  partial void Insertsubject(subject instance);
  partial void Updatesubject(subject instance);
  partial void Deletesubject(subject instance);
  partial void InsertsubjectTeacher(subjectTeacher instance);
  partial void UpdatesubjectTeacher(subjectTeacher instance);
  partial void DeletesubjectTeacher(subjectTeacher instance);
  partial void InsertsupervisingteacherComment(supervisingteacherComment instance);
  partial void UpdatesupervisingteacherComment(supervisingteacherComment instance);
  partial void DeletesupervisingteacherComment(supervisingteacherComment instance);
  partial void Insertteacher(teacher instance);
  partial void Updateteacher(teacher instance);
  partial void Deleteteacher(teacher instance);
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  #endregion
	
	public MOE_DataClassModelDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["MOE_DDatabaseConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public MOE_DataClassModelDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MOE_DataClassModelDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MOE_DataClassModelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public MOE_DataClassModelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<academicYear> academicYears
	{
		get
		{
			return this.GetTable<academicYear>();
		}
	}
	
	public System.Data.Linq.Table<assessment> assessments
	{
		get
		{
			return this.GetTable<assessment>();
		}
	}
	
	public System.Data.Linq.Table<edu_officerComment> edu_officerComments
	{
		get
		{
			return this.GetTable<edu_officerComment>();
		}
	}
	
	public System.Data.Linq.Table<edu_officer> edu_officers
	{
		get
		{
			return this.GetTable<edu_officer>();
		}
	}
	
	public System.Data.Linq.Table<edu_officerSubject> edu_officerSubjects
	{
		get
		{
			return this.GetTable<edu_officerSubject>();
		}
	}
	
	public System.Data.Linq.Table<formclass> formclasses
	{
		get
		{
			return this.GetTable<formclass>();
		}
	}
	
	public System.Data.Linq.Table<generalObjective> generalObjectives
	{
		get
		{
			return this.GetTable<generalObjective>();
		}
	}
	
	public System.Data.Linq.Table<gradeBook> gradeBooks
	{
		get
		{
			return this.GetTable<gradeBook>();
		}
	}
	
	public System.Data.Linq.Table<instructionalMaterial> instructionalMaterials
	{
		get
		{
			return this.GetTable<instructionalMaterial>();
		}
	}
	
	public System.Data.Linq.Table<lessonplanGeneralobjective> lessonplanGeneralobjectives
	{
		get
		{
			return this.GetTable<lessonplanGeneralobjective>();
		}
	}
	
	public System.Data.Linq.Table<lessonplanInstructionalMaterial> lessonplanInstructionalMaterials
	{
		get
		{
			return this.GetTable<lessonplanInstructionalMaterial>();
		}
	}
	
	public System.Data.Linq.Table<lessonPlanMethod> lessonPlanMethods
	{
		get
		{
			return this.GetTable<lessonPlanMethod>();
		}
	}
	
	public System.Data.Linq.Table<lessonplanPlanactivite> lessonplanPlanactivites
	{
		get
		{
			return this.GetTable<lessonplanPlanactivite>();
		}
	}
	
	public System.Data.Linq.Table<lessonplanPlancomment> lessonplanPlancomments
	{
		get
		{
			return this.GetTable<lessonplanPlancomment>();
		}
	}
	
	public System.Data.Linq.Table<lessonPlan> lessonPlans
	{
		get
		{
			return this.GetTable<lessonPlan>();
		}
	}
	
	public System.Data.Linq.Table<lessonplanSpecificobjective> lessonplanSpecificobjectives
	{
		get
		{
			return this.GetTable<lessonplanSpecificobjective>();
		}
	}
	
	public System.Data.Linq.Table<lesssonPlanStep> lesssonPlanSteps
	{
		get
		{
			return this.GetTable<lesssonPlanStep>();
		}
	}
	
	public System.Data.Linq.Table<method> methods
	{
		get
		{
			return this.GetTable<method>();
		}
	}
	
	public System.Data.Linq.Table<planactivity> planactivities
	{
		get
		{
			return this.GetTable<planactivity>();
		}
	}
	
	public System.Data.Linq.Table<plancomment> plancomments
	{
		get
		{
			return this.GetTable<plancomment>();
		}
	}
	
	public System.Data.Linq.Table<specificObjective> specificObjectives
	{
		get
		{
			return this.GetTable<specificObjective>();
		}
	}
	
	public System.Data.Linq.Table<step> steps
	{
		get
		{
			return this.GetTable<step>();
		}
	}
	
	public System.Data.Linq.Table<student> students
	{
		get
		{
			return this.GetTable<student>();
		}
	}
	
	public System.Data.Linq.Table<subject> subjects
	{
		get
		{
			return this.GetTable<subject>();
		}
	}
	
	public System.Data.Linq.Table<subjectTeacher> subjectTeachers
	{
		get
		{
			return this.GetTable<subjectTeacher>();
		}
	}
	
	public System.Data.Linq.Table<supervisingteacherComment> supervisingteacherComments
	{
		get
		{
			return this.GetTable<supervisingteacherComment>();
		}
	}
	
	public System.Data.Linq.Table<teacher> teachers
	{
		get
		{
			return this.GetTable<teacher>();
		}
	}
	
	public System.Data.Linq.Table<user> users
	{
		get
		{
			return this.GetTable<user>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.academicYears")]
public partial class academicYear : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _academicYear_ID;
	
	private string _year;
	
	private System.Nullable<System.DateTime> _startDate;
	
	private System.Nullable<System.DateTime> _endDate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnacademicYear_IDChanging(int value);
    partial void OnacademicYear_IDChanged();
    partial void OnyearChanging(string value);
    partial void OnyearChanged();
    partial void OnstartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnendDateChanged();
    #endregion
	
	public academicYear()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_academicYear_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int academicYear_ID
	{
		get
		{
			return this._academicYear_ID;
		}
		set
		{
			if ((this._academicYear_ID != value))
			{
				this.OnacademicYear_IDChanging(value);
				this.SendPropertyChanging();
				this._academicYear_ID = value;
				this.SendPropertyChanged("academicYear_ID");
				this.OnacademicYear_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year", DbType="VarChar(50)")]
	public string year
	{
		get
		{
			return this._year;
		}
		set
		{
			if ((this._year != value))
			{
				this.OnyearChanging(value);
				this.SendPropertyChanging();
				this._year = value;
				this.SendPropertyChanged("year");
				this.OnyearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="Date")]
	public System.Nullable<System.DateTime> startDate
	{
		get
		{
			return this._startDate;
		}
		set
		{
			if ((this._startDate != value))
			{
				this.OnstartDateChanging(value);
				this.SendPropertyChanging();
				this._startDate = value;
				this.SendPropertyChanged("startDate");
				this.OnstartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="Date")]
	public System.Nullable<System.DateTime> endDate
	{
		get
		{
			return this._endDate;
		}
		set
		{
			if ((this._endDate != value))
			{
				this.OnendDateChanging(value);
				this.SendPropertyChanging();
				this._endDate = value;
				this.SendPropertyChanged("endDate");
				this.OnendDateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.assessments")]
public partial class assessment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _assessment_ID;
	
	private System.Nullable<int> _gradeBook_ID;
	
	private System.Nullable<int> _student_ID;
	
	private System.Nullable<System.DateTime> _dateGiven;
	
	private System.Nullable<decimal> _score;
	
	private System.Nullable<int> _subject_ID;
	
	private string _remarks;
	
	private string _assessmentName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onassessment_IDChanging(int value);
    partial void Onassessment_IDChanged();
    partial void OngradeBook_IDChanging(System.Nullable<int> value);
    partial void OngradeBook_IDChanged();
    partial void Onstudent_IDChanging(System.Nullable<int> value);
    partial void Onstudent_IDChanged();
    partial void OndateGivenChanging(System.Nullable<System.DateTime> value);
    partial void OndateGivenChanged();
    partial void OnscoreChanging(System.Nullable<decimal> value);
    partial void OnscoreChanged();
    partial void Onsubject_IDChanging(System.Nullable<int> value);
    partial void Onsubject_IDChanged();
    partial void OnremarksChanging(string value);
    partial void OnremarksChanged();
    partial void OnassessmentNameChanging(string value);
    partial void OnassessmentNameChanged();
    #endregion
	
	public assessment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assessment_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int assessment_ID
	{
		get
		{
			return this._assessment_ID;
		}
		set
		{
			if ((this._assessment_ID != value))
			{
				this.Onassessment_IDChanging(value);
				this.SendPropertyChanging();
				this._assessment_ID = value;
				this.SendPropertyChanged("assessment_ID");
				this.Onassessment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeBook_ID", DbType="Int")]
	public System.Nullable<int> gradeBook_ID
	{
		get
		{
			return this._gradeBook_ID;
		}
		set
		{
			if ((this._gradeBook_ID != value))
			{
				this.OngradeBook_IDChanging(value);
				this.SendPropertyChanging();
				this._gradeBook_ID = value;
				this.SendPropertyChanged("gradeBook_ID");
				this.OngradeBook_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_ID", DbType="Int")]
	public System.Nullable<int> student_ID
	{
		get
		{
			return this._student_ID;
		}
		set
		{
			if ((this._student_ID != value))
			{
				this.Onstudent_IDChanging(value);
				this.SendPropertyChanging();
				this._student_ID = value;
				this.SendPropertyChanged("student_ID");
				this.Onstudent_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateGiven", DbType="Date")]
	public System.Nullable<System.DateTime> dateGiven
	{
		get
		{
			return this._dateGiven;
		}
		set
		{
			if ((this._dateGiven != value))
			{
				this.OndateGivenChanging(value);
				this.SendPropertyChanging();
				this._dateGiven = value;
				this.SendPropertyChanged("dateGiven");
				this.OndateGivenChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score", DbType="Decimal(18,0)")]
	public System.Nullable<decimal> score
	{
		get
		{
			return this._score;
		}
		set
		{
			if ((this._score != value))
			{
				this.OnscoreChanging(value);
				this.SendPropertyChanging();
				this._score = value;
				this.SendPropertyChanged("score");
				this.OnscoreChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_ID", DbType="Int")]
	public System.Nullable<int> subject_ID
	{
		get
		{
			return this._subject_ID;
		}
		set
		{
			if ((this._subject_ID != value))
			{
				this.Onsubject_IDChanging(value);
				this.SendPropertyChanging();
				this._subject_ID = value;
				this.SendPropertyChanged("subject_ID");
				this.Onsubject_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remarks", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string remarks
	{
		get
		{
			return this._remarks;
		}
		set
		{
			if ((this._remarks != value))
			{
				this.OnremarksChanging(value);
				this.SendPropertyChanging();
				this._remarks = value;
				this.SendPropertyChanged("remarks");
				this.OnremarksChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_assessmentName", DbType="VarChar(50)")]
	public string assessmentName
	{
		get
		{
			return this._assessmentName;
		}
		set
		{
			if ((this._assessmentName != value))
			{
				this.OnassessmentNameChanging(value);
				this.SendPropertyChanging();
				this._assessmentName = value;
				this.SendPropertyChanged("assessmentName");
				this.OnassessmentNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.edu_officerComments")]
public partial class edu_officerComment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _edu_officer_ID;
	
	private int _lessonPlan_ID;
	
	private string _Comment;
	
	private System.Nullable<System.DateTime> _dateOfComment;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onedu_officer_IDChanging(int value);
    partial void Onedu_officer_IDChanged();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OndateOfCommentChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfCommentChanged();
    #endregion
	
	public edu_officerComment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edu_officer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int edu_officer_ID
	{
		get
		{
			return this._edu_officer_ID;
		}
		set
		{
			if ((this._edu_officer_ID != value))
			{
				this.Onedu_officer_IDChanging(value);
				this.SendPropertyChanging();
				this._edu_officer_ID = value;
				this.SendPropertyChanged("edu_officer_ID");
				this.Onedu_officer_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string Comment
	{
		get
		{
			return this._Comment;
		}
		set
		{
			if ((this._Comment != value))
			{
				this.OnCommentChanging(value);
				this.SendPropertyChanging();
				this._Comment = value;
				this.SendPropertyChanged("Comment");
				this.OnCommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfComment", DbType="Date")]
	public System.Nullable<System.DateTime> dateOfComment
	{
		get
		{
			return this._dateOfComment;
		}
		set
		{
			if ((this._dateOfComment != value))
			{
				this.OndateOfCommentChanging(value);
				this.SendPropertyChanging();
				this._dateOfComment = value;
				this.SendPropertyChanged("dateOfComment");
				this.OndateOfCommentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.edu_officers")]
public partial class edu_officer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _edu_officer_ID;
	
	private string _firstName;
	
	private string _lastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private string _position;
	
	private System.Nullable<int> _user_ID;
	
	private string _middleName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onedu_officer_IDChanging(int value);
    partial void Onedu_officer_IDChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    partial void Onuser_IDChanging(System.Nullable<int> value);
    partial void Onuser_IDChanged();
    partial void OnmiddleNameChanging(string value);
    partial void OnmiddleNameChanged();
    #endregion
	
	public edu_officer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edu_officer_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int edu_officer_ID
	{
		get
		{
			return this._edu_officer_ID;
		}
		set
		{
			if ((this._edu_officer_ID != value))
			{
				this.Onedu_officer_IDChanging(value);
				this.SendPropertyChanging();
				this._edu_officer_ID = value;
				this.SendPropertyChanged("edu_officer_ID");
				this.Onedu_officer_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(50)")]
	public string firstName
	{
		get
		{
			return this._firstName;
		}
		set
		{
			if ((this._firstName != value))
			{
				this.OnfirstNameChanging(value);
				this.SendPropertyChanging();
				this._firstName = value;
				this.SendPropertyChanged("firstName");
				this.OnfirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(50)")]
	public string lastName
	{
		get
		{
			return this._lastName;
		}
		set
		{
			if ((this._lastName != value))
			{
				this.OnlastNameChanging(value);
				this.SendPropertyChanging();
				this._lastName = value;
				this.SendPropertyChanged("lastName");
				this.OnlastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
	public string position
	{
		get
		{
			return this._position;
		}
		set
		{
			if ((this._position != value))
			{
				this.OnpositionChanging(value);
				this.SendPropertyChanging();
				this._position = value;
				this.SendPropertyChanged("position");
				this.OnpositionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ID", DbType="Int")]
	public System.Nullable<int> user_ID
	{
		get
		{
			return this._user_ID;
		}
		set
		{
			if ((this._user_ID != value))
			{
				this.Onuser_IDChanging(value);
				this.SendPropertyChanging();
				this._user_ID = value;
				this.SendPropertyChanged("user_ID");
				this.Onuser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="VarChar(50)")]
	public string middleName
	{
		get
		{
			return this._middleName;
		}
		set
		{
			if ((this._middleName != value))
			{
				this.OnmiddleNameChanging(value);
				this.SendPropertyChanging();
				this._middleName = value;
				this.SendPropertyChanged("middleName");
				this.OnmiddleNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.edu_officerSubjects")]
public partial class edu_officerSubject : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _edu_officer_ID;
	
	private int _subject_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onedu_officer_IDChanging(int value);
    partial void Onedu_officer_IDChanged();
    partial void Onsubject_IDChanging(int value);
    partial void Onsubject_IDChanged();
    #endregion
	
	public edu_officerSubject()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edu_officer_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int edu_officer_ID
	{
		get
		{
			return this._edu_officer_ID;
		}
		set
		{
			if ((this._edu_officer_ID != value))
			{
				this.Onedu_officer_IDChanging(value);
				this.SendPropertyChanging();
				this._edu_officer_ID = value;
				this.SendPropertyChanged("edu_officer_ID");
				this.Onedu_officer_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int subject_ID
	{
		get
		{
			return this._subject_ID;
		}
		set
		{
			if ((this._subject_ID != value))
			{
				this.Onsubject_IDChanging(value);
				this.SendPropertyChanging();
				this._subject_ID = value;
				this.SendPropertyChanged("subject_ID");
				this.Onsubject_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.formclasses")]
public partial class formclass : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _formclass_ID;
	
	private string _name;
	
	private string _room;
	
	private System.Nullable<int> _teacher_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onformclass_IDChanging(int value);
    partial void Onformclass_IDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnroomChanging(string value);
    partial void OnroomChanged();
    partial void Onteacher_IDChanging(System.Nullable<int> value);
    partial void Onteacher_IDChanged();
    #endregion
	
	public formclass()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formclass_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int formclass_ID
	{
		get
		{
			return this._formclass_ID;
		}
		set
		{
			if ((this._formclass_ID != value))
			{
				this.Onformclass_IDChanging(value);
				this.SendPropertyChanging();
				this._formclass_ID = value;
				this.SendPropertyChanged("formclass_ID");
				this.Onformclass_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_room", DbType="VarChar(50)")]
	public string room
	{
		get
		{
			return this._room;
		}
		set
		{
			if ((this._room != value))
			{
				this.OnroomChanging(value);
				this.SendPropertyChanging();
				this._room = value;
				this.SendPropertyChanged("room");
				this.OnroomChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", DbType="Int")]
	public System.Nullable<int> teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.generalObjectives")]
public partial class generalObjective : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _generalObjective_ID;
	
	private string _objective;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngeneralObjective_IDChanging(int value);
    partial void OngeneralObjective_IDChanged();
    partial void OnobjectiveChanging(string value);
    partial void OnobjectiveChanged();
    #endregion
	
	public generalObjective()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_generalObjective_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int generalObjective_ID
	{
		get
		{
			return this._generalObjective_ID;
		}
		set
		{
			if ((this._generalObjective_ID != value))
			{
				this.OngeneralObjective_IDChanging(value);
				this.SendPropertyChanging();
				this._generalObjective_ID = value;
				this.SendPropertyChanged("generalObjective_ID");
				this.OngeneralObjective_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objective", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string objective
	{
		get
		{
			return this._objective;
		}
		set
		{
			if ((this._objective != value))
			{
				this.OnobjectiveChanging(value);
				this.SendPropertyChanging();
				this._objective = value;
				this.SendPropertyChanged("objective");
				this.OnobjectiveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.gradeBooks")]
public partial class gradeBook : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gradeBook_ID;
	
	private System.Nullable<int> _academicYear_ID;
	
	private System.Nullable<int> _teacher_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngradeBook_IDChanging(int value);
    partial void OngradeBook_IDChanged();
    partial void OnacademicYear_IDChanging(System.Nullable<int> value);
    partial void OnacademicYear_IDChanged();
    partial void Onteacher_IDChanging(System.Nullable<int> value);
    partial void Onteacher_IDChanged();
    #endregion
	
	public gradeBook()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeBook_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gradeBook_ID
	{
		get
		{
			return this._gradeBook_ID;
		}
		set
		{
			if ((this._gradeBook_ID != value))
			{
				this.OngradeBook_IDChanging(value);
				this.SendPropertyChanging();
				this._gradeBook_ID = value;
				this.SendPropertyChanged("gradeBook_ID");
				this.OngradeBook_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_academicYear_ID", DbType="Int")]
	public System.Nullable<int> academicYear_ID
	{
		get
		{
			return this._academicYear_ID;
		}
		set
		{
			if ((this._academicYear_ID != value))
			{
				this.OnacademicYear_IDChanging(value);
				this.SendPropertyChanging();
				this._academicYear_ID = value;
				this.SendPropertyChanged("academicYear_ID");
				this.OnacademicYear_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", DbType="Int")]
	public System.Nullable<int> teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.instructionalMaterials")]
public partial class instructionalMaterial : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _instructionalMaterials_ID;
	
	private string _material;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OninstructionalMaterials_IDChanging(int value);
    partial void OninstructionalMaterials_IDChanged();
    partial void OnmaterialChanging(string value);
    partial void OnmaterialChanged();
    #endregion
	
	public instructionalMaterial()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructionalMaterials_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int instructionalMaterials_ID
	{
		get
		{
			return this._instructionalMaterials_ID;
		}
		set
		{
			if ((this._instructionalMaterials_ID != value))
			{
				this.OninstructionalMaterials_IDChanging(value);
				this.SendPropertyChanging();
				this._instructionalMaterials_ID = value;
				this.SendPropertyChanged("instructionalMaterials_ID");
				this.OninstructionalMaterials_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_material", DbType="VarChar(50)")]
	public string material
	{
		get
		{
			return this._material;
		}
		set
		{
			if ((this._material != value))
			{
				this.OnmaterialChanging(value);
				this.SendPropertyChanging();
				this._material = value;
				this.SendPropertyChanged("material");
				this.OnmaterialChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonplanGeneralobjectives")]
public partial class lessonplanGeneralobjective
{
	
	private System.Nullable<int> _generalObjective_ID;
	
	private System.Nullable<int> _lessonPlan_ID;
	
	public lessonplanGeneralobjective()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_generalObjective_ID", DbType="Int")]
	public System.Nullable<int> generalObjective_ID
	{
		get
		{
			return this._generalObjective_ID;
		}
		set
		{
			if ((this._generalObjective_ID != value))
			{
				this._generalObjective_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int")]
	public System.Nullable<int> lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this._lessonPlan_ID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonplanInstructionalMaterials")]
public partial class lessonplanInstructionalMaterial
{
	
	private System.Nullable<int> _lessonPlan_ID;
	
	private System.Nullable<int> _instructionalMaterials_ID;
	
	public lessonplanInstructionalMaterial()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int")]
	public System.Nullable<int> lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this._lessonPlan_ID = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instructionalMaterials_ID", DbType="Int")]
	public System.Nullable<int> instructionalMaterials_ID
	{
		get
		{
			return this._instructionalMaterials_ID;
		}
		set
		{
			if ((this._instructionalMaterials_ID != value))
			{
				this._instructionalMaterials_ID = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonPlanMethods")]
public partial class lessonPlanMethod : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _lessonPlan_ID;
	
	private int _method_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    partial void Onmethod_IDChanging(int value);
    partial void Onmethod_IDChanged();
    #endregion
	
	public lessonPlanMethod()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int method_ID
	{
		get
		{
			return this._method_ID;
		}
		set
		{
			if ((this._method_ID != value))
			{
				this.Onmethod_IDChanging(value);
				this.SendPropertyChanging();
				this._method_ID = value;
				this.SendPropertyChanged("method_ID");
				this.Onmethod_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonplanPlanactivites")]
public partial class lessonplanPlanactivite : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _planActivity_ID;
	
	private int _lessonPlan_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplanActivity_IDChanging(int value);
    partial void OnplanActivity_IDChanged();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    #endregion
	
	public lessonplanPlanactivite()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planActivity_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int planActivity_ID
	{
		get
		{
			return this._planActivity_ID;
		}
		set
		{
			if ((this._planActivity_ID != value))
			{
				this.OnplanActivity_IDChanging(value);
				this.SendPropertyChanging();
				this._planActivity_ID = value;
				this.SendPropertyChanged("planActivity_ID");
				this.OnplanActivity_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonplanPlancomments")]
public partial class lessonplanPlancomment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _lessonplan_ID;
	
	private int _plancomment_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onlessonplan_IDChanging(int value);
    partial void Onlessonplan_IDChanged();
    partial void Onplancomment_IDChanging(int value);
    partial void Onplancomment_IDChanged();
    #endregion
	
	public lessonplanPlancomment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonplan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonplan_ID
	{
		get
		{
			return this._lessonplan_ID;
		}
		set
		{
			if ((this._lessonplan_ID != value))
			{
				this.Onlessonplan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonplan_ID = value;
				this.SendPropertyChanged("lessonplan_ID");
				this.Onlessonplan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plancomment_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int plancomment_ID
	{
		get
		{
			return this._plancomment_ID;
		}
		set
		{
			if ((this._plancomment_ID != value))
			{
				this.Onplancomment_IDChanging(value);
				this.SendPropertyChanging();
				this._plancomment_ID = value;
				this.SendPropertyChanged("plancomment_ID");
				this.Onplancomment_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonPlans")]
public partial class lessonPlan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _lessonPlan_ID;
	
	private System.Nullable<int> _teacher_ID;
	
	private System.Nullable<int> _subject_ID;
	
	private System.Nullable<System.DateTime> _startDate;
	
	private System.Nullable<System.DateTime> _endDate;
	
	private string _duration;
	
	private string _topic;
	
	private string _subtopic;
	
	private System.Nullable<int> _formClass_ID;
	
	private string _PreviousKnowledge;
	
	private string _plannedContent;
	
	private string _introduction;
	
	private string _evaluations;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    partial void Onteacher_IDChanging(System.Nullable<int> value);
    partial void Onteacher_IDChanged();
    partial void Onsubject_IDChanging(System.Nullable<int> value);
    partial void Onsubject_IDChanged();
    partial void OnstartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnstartDateChanged();
    partial void OnendDateChanging(System.Nullable<System.DateTime> value);
    partial void OnendDateChanged();
    partial void OndurationChanging(string value);
    partial void OndurationChanged();
    partial void OntopicChanging(string value);
    partial void OntopicChanged();
    partial void OnsubtopicChanging(string value);
    partial void OnsubtopicChanged();
    partial void OnformClass_IDChanging(System.Nullable<int> value);
    partial void OnformClass_IDChanged();
    partial void OnPreviousKnowledgeChanging(string value);
    partial void OnPreviousKnowledgeChanged();
    partial void OnplannedContentChanging(string value);
    partial void OnplannedContentChanged();
    partial void OnintroductionChanging(string value);
    partial void OnintroductionChanged();
    partial void OnevaluationsChanging(string value);
    partial void OnevaluationsChanged();
    #endregion
	
	public lessonPlan()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", DbType="Int")]
	public System.Nullable<int> teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_ID", DbType="Int")]
	public System.Nullable<int> subject_ID
	{
		get
		{
			return this._subject_ID;
		}
		set
		{
			if ((this._subject_ID != value))
			{
				this.Onsubject_IDChanging(value);
				this.SendPropertyChanging();
				this._subject_ID = value;
				this.SendPropertyChanged("subject_ID");
				this.Onsubject_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startDate", DbType="Date")]
	public System.Nullable<System.DateTime> startDate
	{
		get
		{
			return this._startDate;
		}
		set
		{
			if ((this._startDate != value))
			{
				this.OnstartDateChanging(value);
				this.SendPropertyChanging();
				this._startDate = value;
				this.SendPropertyChanged("startDate");
				this.OnstartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_endDate", DbType="Date")]
	public System.Nullable<System.DateTime> endDate
	{
		get
		{
			return this._endDate;
		}
		set
		{
			if ((this._endDate != value))
			{
				this.OnendDateChanging(value);
				this.SendPropertyChanging();
				this._endDate = value;
				this.SendPropertyChanged("endDate");
				this.OnendDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_duration", DbType="VarChar(50)")]
	public string duration
	{
		get
		{
			return this._duration;
		}
		set
		{
			if ((this._duration != value))
			{
				this.OndurationChanging(value);
				this.SendPropertyChanging();
				this._duration = value;
				this.SendPropertyChanged("duration");
				this.OndurationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_topic", DbType="VarChar(50)")]
	public string topic
	{
		get
		{
			return this._topic;
		}
		set
		{
			if ((this._topic != value))
			{
				this.OntopicChanging(value);
				this.SendPropertyChanging();
				this._topic = value;
				this.SendPropertyChanged("topic");
				this.OntopicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subtopic", DbType="VarChar(50)")]
	public string subtopic
	{
		get
		{
			return this._subtopic;
		}
		set
		{
			if ((this._subtopic != value))
			{
				this.OnsubtopicChanging(value);
				this.SendPropertyChanging();
				this._subtopic = value;
				this.SendPropertyChanged("subtopic");
				this.OnsubtopicChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_formClass_ID", DbType="Int")]
	public System.Nullable<int> formClass_ID
	{
		get
		{
			return this._formClass_ID;
		}
		set
		{
			if ((this._formClass_ID != value))
			{
				this.OnformClass_IDChanging(value);
				this.SendPropertyChanging();
				this._formClass_ID = value;
				this.SendPropertyChanged("formClass_ID");
				this.OnformClass_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreviousKnowledge", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string PreviousKnowledge
	{
		get
		{
			return this._PreviousKnowledge;
		}
		set
		{
			if ((this._PreviousKnowledge != value))
			{
				this.OnPreviousKnowledgeChanging(value);
				this.SendPropertyChanging();
				this._PreviousKnowledge = value;
				this.SendPropertyChanged("PreviousKnowledge");
				this.OnPreviousKnowledgeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plannedContent", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string plannedContent
	{
		get
		{
			return this._plannedContent;
		}
		set
		{
			if ((this._plannedContent != value))
			{
				this.OnplannedContentChanging(value);
				this.SendPropertyChanging();
				this._plannedContent = value;
				this.SendPropertyChanged("plannedContent");
				this.OnplannedContentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_introduction", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string introduction
	{
		get
		{
			return this._introduction;
		}
		set
		{
			if ((this._introduction != value))
			{
				this.OnintroductionChanging(value);
				this.SendPropertyChanging();
				this._introduction = value;
				this.SendPropertyChanged("introduction");
				this.OnintroductionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evaluations", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string evaluations
	{
		get
		{
			return this._evaluations;
		}
		set
		{
			if ((this._evaluations != value))
			{
				this.OnevaluationsChanging(value);
				this.SendPropertyChanging();
				this._evaluations = value;
				this.SendPropertyChanged("evaluations");
				this.OnevaluationsChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lessonplanSpecificobjectives")]
public partial class lessonplanSpecificobjective : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _specificObjective_ID;
	
	private int _lessonPlan_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnspecificObjective_IDChanging(int value);
    partial void OnspecificObjective_IDChanged();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    #endregion
	
	public lessonplanSpecificobjective()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specificObjective_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int specificObjective_ID
	{
		get
		{
			return this._specificObjective_ID;
		}
		set
		{
			if ((this._specificObjective_ID != value))
			{
				this.OnspecificObjective_IDChanging(value);
				this.SendPropertyChanging();
				this._specificObjective_ID = value;
				this.SendPropertyChanged("specificObjective_ID");
				this.OnspecificObjective_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.lesssonPlanSteps")]
public partial class lesssonPlanStep : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _lessonPlan_ID;
	
	private int _step_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    partial void Onstep_IDChanging(int value);
    partial void Onstep_IDChanged();
    #endregion
	
	public lesssonPlanStep()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int step_ID
	{
		get
		{
			return this._step_ID;
		}
		set
		{
			if ((this._step_ID != value))
			{
				this.Onstep_IDChanging(value);
				this.SendPropertyChanging();
				this._step_ID = value;
				this.SendPropertyChanged("step_ID");
				this.Onstep_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.methods")]
public partial class method : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _method_ID;
	
	private string _name;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmethod_IDChanging(int value);
    partial void Onmethod_IDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    #endregion
	
	public method()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_method_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int method_ID
	{
		get
		{
			return this._method_ID;
		}
		set
		{
			if ((this._method_ID != value))
			{
				this.Onmethod_IDChanging(value);
				this.SendPropertyChanging();
				this._method_ID = value;
				this.SendPropertyChanged("method_ID");
				this.Onmethod_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.planactivities")]
public partial class planactivity : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _planActivity_ID;
	
	private string _activity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnplanActivity_IDChanging(int value);
    partial void OnplanActivity_IDChanged();
    partial void OnactivityChanging(string value);
    partial void OnactivityChanged();
    #endregion
	
	public planactivity()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planActivity_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int planActivity_ID
	{
		get
		{
			return this._planActivity_ID;
		}
		set
		{
			if ((this._planActivity_ID != value))
			{
				this.OnplanActivity_IDChanging(value);
				this.SendPropertyChanging();
				this._planActivity_ID = value;
				this.SendPropertyChanged("planActivity_ID");
				this.OnplanActivity_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activity", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string activity
	{
		get
		{
			return this._activity;
		}
		set
		{
			if ((this._activity != value))
			{
				this.OnactivityChanging(value);
				this.SendPropertyChanging();
				this._activity = value;
				this.SendPropertyChanged("activity");
				this.OnactivityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.plancomments")]
public partial class plancomment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _plancomment_ID;
	
	private string _comment;
	
	private System.Nullable<System.DateTime> _dateOfComment;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onplancomment_IDChanging(int value);
    partial void Onplancomment_IDChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OndateOfCommentChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfCommentChanged();
    #endregion
	
	public plancomment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plancomment_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int plancomment_ID
	{
		get
		{
			return this._plancomment_ID;
		}
		set
		{
			if ((this._plancomment_ID != value))
			{
				this.Onplancomment_IDChanging(value);
				this.SendPropertyChanging();
				this._plancomment_ID = value;
				this.SendPropertyChanged("plancomment_ID");
				this.Onplancomment_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfComment", DbType="DateTime")]
	public System.Nullable<System.DateTime> dateOfComment
	{
		get
		{
			return this._dateOfComment;
		}
		set
		{
			if ((this._dateOfComment != value))
			{
				this.OndateOfCommentChanging(value);
				this.SendPropertyChanging();
				this._dateOfComment = value;
				this.SendPropertyChanged("dateOfComment");
				this.OndateOfCommentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.specificObjectives")]
public partial class specificObjective : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _specificObjective_ID;
	
	private string _objective;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnspecificObjective_IDChanging(int value);
    partial void OnspecificObjective_IDChanged();
    partial void OnobjectiveChanging(string value);
    partial void OnobjectiveChanged();
    #endregion
	
	public specificObjective()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specificObjective_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int specificObjective_ID
	{
		get
		{
			return this._specificObjective_ID;
		}
		set
		{
			if ((this._specificObjective_ID != value))
			{
				this.OnspecificObjective_IDChanging(value);
				this.SendPropertyChanging();
				this._specificObjective_ID = value;
				this.SendPropertyChanged("specificObjective_ID");
				this.OnspecificObjective_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_objective", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string objective
	{
		get
		{
			return this._objective;
		}
		set
		{
			if ((this._objective != value))
			{
				this.OnobjectiveChanging(value);
				this.SendPropertyChanging();
				this._objective = value;
				this.SendPropertyChanged("objective");
				this.OnobjectiveChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.steps")]
public partial class step : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _step_ID;
	
	private System.Nullable<int> _stepNumber;
	
	private string _lessonStep;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstep_IDChanging(int value);
    partial void Onstep_IDChanged();
    partial void OnstepNumberChanging(System.Nullable<int> value);
    partial void OnstepNumberChanged();
    partial void OnlessonStepChanging(string value);
    partial void OnlessonStepChanged();
    #endregion
	
	public step()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_step_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int step_ID
	{
		get
		{
			return this._step_ID;
		}
		set
		{
			if ((this._step_ID != value))
			{
				this.Onstep_IDChanging(value);
				this.SendPropertyChanging();
				this._step_ID = value;
				this.SendPropertyChanged("step_ID");
				this.Onstep_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stepNumber", DbType="Int")]
	public System.Nullable<int> stepNumber
	{
		get
		{
			return this._stepNumber;
		}
		set
		{
			if ((this._stepNumber != value))
			{
				this.OnstepNumberChanging(value);
				this.SendPropertyChanging();
				this._stepNumber = value;
				this.SendPropertyChanged("stepNumber");
				this.OnstepNumberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonStep", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string lessonStep
	{
		get
		{
			return this._lessonStep;
		}
		set
		{
			if ((this._lessonStep != value))
			{
				this.OnlessonStepChanging(value);
				this.SendPropertyChanging();
				this._lessonStep = value;
				this.SendPropertyChanged("lessonStep");
				this.OnlessonStepChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.students")]
public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _student_id;
	
	private string _firstName;
	
	private string _middleName;
	
	private string _lastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onstudent_idChanging(int value);
    partial void Onstudent_idChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnmiddleNameChanging(string value);
    partial void OnmiddleNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    #endregion
	
	public student()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_student_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int student_id
	{
		get
		{
			return this._student_id;
		}
		set
		{
			if ((this._student_id != value))
			{
				this.Onstudent_idChanging(value);
				this.SendPropertyChanging();
				this._student_id = value;
				this.SendPropertyChanged("student_id");
				this.Onstudent_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(50)")]
	public string firstName
	{
		get
		{
			return this._firstName;
		}
		set
		{
			if ((this._firstName != value))
			{
				this.OnfirstNameChanging(value);
				this.SendPropertyChanging();
				this._firstName = value;
				this.SendPropertyChanged("firstName");
				this.OnfirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="VarChar(50)")]
	public string middleName
	{
		get
		{
			return this._middleName;
		}
		set
		{
			if ((this._middleName != value))
			{
				this.OnmiddleNameChanging(value);
				this.SendPropertyChanging();
				this._middleName = value;
				this.SendPropertyChanged("middleName");
				this.OnmiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(50)")]
	public string lastName
	{
		get
		{
			return this._lastName;
		}
		set
		{
			if ((this._lastName != value))
			{
				this.OnlastNameChanging(value);
				this.SendPropertyChanging();
				this._lastName = value;
				this.SendPropertyChanged("lastName");
				this.OnlastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subjects")]
public partial class subject : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _subject_ID;
	
	private string _name;
	
	private string _description;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsubject_IDChanging(int value);
    partial void Onsubject_IDChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
	
	public subject()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int subject_ID
	{
		get
		{
			return this._subject_ID;
		}
		set
		{
			if ((this._subject_ID != value))
			{
				this.Onsubject_IDChanging(value);
				this.SendPropertyChanging();
				this._subject_ID = value;
				this.SendPropertyChanged("subject_ID");
				this.Onsubject_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
	public string name
	{
		get
		{
			return this._name;
		}
		set
		{
			if ((this._name != value))
			{
				this.OnnameChanging(value);
				this.SendPropertyChanging();
				this._name = value;
				this.SendPropertyChanged("name");
				this.OnnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.subjectTeachers")]
public partial class subjectTeacher : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _teacher_ID;
	
	private int _subject_ID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onteacher_IDChanging(int value);
    partial void Onteacher_IDChanged();
    partial void Onsubject_IDChanging(int value);
    partial void Onsubject_IDChanged();
    #endregion
	
	public subjectTeacher()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int subject_ID
	{
		get
		{
			return this._subject_ID;
		}
		set
		{
			if ((this._subject_ID != value))
			{
				this.Onsubject_IDChanging(value);
				this.SendPropertyChanging();
				this._subject_ID = value;
				this.SendPropertyChanged("subject_ID");
				this.Onsubject_IDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.supervisingteacherComments")]
public partial class supervisingteacherComment : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _teacher_ID;
	
	private int _lessonPlan_ID;
	
	private string _comment;
	
	private System.Nullable<System.DateTime> _dateOfComment;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onteacher_IDChanging(int value);
    partial void Onteacher_IDChanged();
    partial void OnlessonPlan_IDChanging(int value);
    partial void OnlessonPlan_IDChanged();
    partial void OncommentChanging(string value);
    partial void OncommentChanged();
    partial void OndateOfCommentChanging(System.Nullable<System.DateTime> value);
    partial void OndateOfCommentChanged();
    #endregion
	
	public supervisingteacherComment()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lessonPlan_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int lessonPlan_ID
	{
		get
		{
			return this._lessonPlan_ID;
		}
		set
		{
			if ((this._lessonPlan_ID != value))
			{
				this.OnlessonPlan_IDChanging(value);
				this.SendPropertyChanging();
				this._lessonPlan_ID = value;
				this.SendPropertyChanged("lessonPlan_ID");
				this.OnlessonPlan_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="Text", UpdateCheck=UpdateCheck.Never)]
	public string comment
	{
		get
		{
			return this._comment;
		}
		set
		{
			if ((this._comment != value))
			{
				this.OncommentChanging(value);
				this.SendPropertyChanging();
				this._comment = value;
				this.SendPropertyChanged("comment");
				this.OncommentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dateOfComment", DbType="Date")]
	public System.Nullable<System.DateTime> dateOfComment
	{
		get
		{
			return this._dateOfComment;
		}
		set
		{
			if ((this._dateOfComment != value))
			{
				this.OndateOfCommentChanging(value);
				this.SendPropertyChanging();
				this._dateOfComment = value;
				this.SendPropertyChanged("dateOfComment");
				this.OndateOfCommentChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.teachers")]
public partial class teacher : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _teacher_ID;
	
	private string _firstName;
	
	private string _middleName;
	
	private string _lastName;
	
	private System.Nullable<System.DateTime> _DOB;
	
	private System.Nullable<int> _user__ID;
	
	private string _position;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onteacher_IDChanging(int value);
    partial void Onteacher_IDChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnmiddleNameChanging(string value);
    partial void OnmiddleNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void Onuser__IDChanging(System.Nullable<int> value);
    partial void Onuser__IDChanged();
    partial void OnpositionChanging(string value);
    partial void OnpositionChanged();
    #endregion
	
	public teacher()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teacher_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int teacher_ID
	{
		get
		{
			return this._teacher_ID;
		}
		set
		{
			if ((this._teacher_ID != value))
			{
				this.Onteacher_IDChanging(value);
				this.SendPropertyChanging();
				this._teacher_ID = value;
				this.SendPropertyChanged("teacher_ID");
				this.Onteacher_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(50)")]
	public string firstName
	{
		get
		{
			return this._firstName;
		}
		set
		{
			if ((this._firstName != value))
			{
				this.OnfirstNameChanging(value);
				this.SendPropertyChanging();
				this._firstName = value;
				this.SendPropertyChanged("firstName");
				this.OnfirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_middleName", DbType="VarChar(50)")]
	public string middleName
	{
		get
		{
			return this._middleName;
		}
		set
		{
			if ((this._middleName != value))
			{
				this.OnmiddleNameChanging(value);
				this.SendPropertyChanging();
				this._middleName = value;
				this.SendPropertyChanged("middleName");
				this.OnmiddleNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(50)")]
	public string lastName
	{
		get
		{
			return this._lastName;
		}
		set
		{
			if ((this._lastName != value))
			{
				this.OnlastNameChanging(value);
				this.SendPropertyChanging();
				this._lastName = value;
				this.SendPropertyChanged("lastName");
				this.OnlastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="Date")]
	public System.Nullable<System.DateTime> DOB
	{
		get
		{
			return this._DOB;
		}
		set
		{
			if ((this._DOB != value))
			{
				this.OnDOBChanging(value);
				this.SendPropertyChanging();
				this._DOB = value;
				this.SendPropertyChanged("DOB");
				this.OnDOBChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user__ID", DbType="Int")]
	public System.Nullable<int> user__ID
	{
		get
		{
			return this._user__ID;
		}
		set
		{
			if ((this._user__ID != value))
			{
				this.Onuser__IDChanging(value);
				this.SendPropertyChanging();
				this._user__ID = value;
				this.SendPropertyChanged("user__ID");
				this.Onuser__IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_position", DbType="VarChar(50)")]
	public string position
	{
		get
		{
			return this._position;
		}
		set
		{
			if ((this._position != value))
			{
				this.OnpositionChanging(value);
				this.SendPropertyChanging();
				this._position = value;
				this.SendPropertyChanged("position");
				this.OnpositionChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.users")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _user_ID;
	
	private string _userName;
	
	private string _email;
	
	private string _password;
	
	private System.Nullable<bool> _isSchoolAdmin;
	
	private System.Nullable<bool> _isMinistryAdmin;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_IDChanging(int value);
    partial void Onuser_IDChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnisSchoolAdminChanging(System.Nullable<bool> value);
    partial void OnisSchoolAdminChanged();
    partial void OnisMinistryAdminChanging(System.Nullable<bool> value);
    partial void OnisMinistryAdminChanged();
    #endregion
	
	public user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int user_ID
	{
		get
		{
			return this._user_ID;
		}
		set
		{
			if ((this._user_ID != value))
			{
				this.Onuser_IDChanging(value);
				this.SendPropertyChanging();
				this._user_ID = value;
				this.SendPropertyChanged("user_ID");
				this.Onuser_IDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(50)")]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(250)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isSchoolAdmin", DbType="Bit")]
	public System.Nullable<bool> isSchoolAdmin
	{
		get
		{
			return this._isSchoolAdmin;
		}
		set
		{
			if ((this._isSchoolAdmin != value))
			{
				this.OnisSchoolAdminChanging(value);
				this.SendPropertyChanging();
				this._isSchoolAdmin = value;
				this.SendPropertyChanged("isSchoolAdmin");
				this.OnisSchoolAdminChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isMinistryAdmin", DbType="Bit")]
	public System.Nullable<bool> isMinistryAdmin
	{
		get
		{
			return this._isMinistryAdmin;
		}
		set
		{
			if ((this._isMinistryAdmin != value))
			{
				this.OnisMinistryAdminChanging(value);
				this.SendPropertyChanging();
				this._isMinistryAdmin = value;
				this.SendPropertyChanged("isMinistryAdmin");
				this.OnisMinistryAdminChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
